from fastapi import status

class HTTPStatus:
    SUCCESS = status.HTTP_200_OK
    CREATED = status.HTTP_201_CREATED

    BAD_REQUEST = status.HTTP_400_BAD_REQUEST
    UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
    FORBIDDEN = status.HTTP_403_FORBIDDEN
    NOT_FOUND = status.HTTP_404_NOT_FOUND

    VALIDATION_ERROR = status.HTTP_422_UNPROCESSABLE_ENTITY

    SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR